---
title: Doom-Emacs
date: 2021-02-06
categories:
  - emacs
tags:
    - emacs
---
#+Learning-Emacs:

* Intro
i'm new to eamcs.And now i'm writing this article with /`Doom Emacs`/.Its really awesome!
Using the laptop of win10 and run eamcs in terminal with wsl2. All thing go pretty well...
But i'm not familiar with doom eamcs.I don't like remember the key-binding,i prefer remember key-binding by doing some actually jobs.

Although doom eamcs has good documents,but i still can not .
* There are some problems i need to fix
i decide to learning it by actually works. So this may look kinds of weird.Anyway , just do it.

** DONE Change Evil's mode (such as: text-mode vision-mode et..)
my mistake,there's no thing i need to do,because the key-binding is convince.
Just type `C-g` and you can escape from everywhere!!!!


** DONE English Spell Checker plugin

** DONE Move around the Windows
Ok You can use `SPC-w` as the window manager prefix key and you can move cursor between the windows

** DONE What's the different between Window and Buffer?
    Window: windows is a interface between user and emacs
    Buffer: buffer like cache between file and system memory
* There are some problems i need to fix
i decide to learning it by actually works. So this may look kinds of weird.Anyway , just do it.

** DONE Change Evil's mode (such as: text-mode vision-mode et..)
my mistake,there's no thing i need to do,because the key-binding is convince.
Just type `C-g` and you can escape from everywhere!!!!


** DONE English Spell Checker plugin

** DONE Move around the Windows
Ok You can use `SPC-w` as the window manager prefix key and you can move cursor between the windows

** DONE What's the different between Window and Buffer?
    Window: windows is a interface between user and emacs
    Buffer: buffer like cache between file and system memory
